name: Run test & Android Build (debug)
on:
  pull_request:
    branches:
      - test
    types:
      - 'opened'
      - 'synchronize'
      - 'edited'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: {{VALUES_APP_NAME}}-build-debug
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/android-build.yml
    with:
      build_type: 'debug'
      run_tests: true
      comment_on_pr: true
