name: Run Unit Tests
on:
  pull_request:
    branches:
      - test
      - main
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
  workflow_dispatch:

concurrency:
  group: XXX-run-test
  cancel-in-progress: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew test
